#!/usr/bin/env python3
"""Render the ControlPlane README PDF (T7.2).

Generated by script so it cannot drift from the repo. Pulls the REAL eval and
bench numbers from evals/last_run.json and submission/latency_bench.json so the
capability ledger and evidence section always match what `make eval` / `make bench`
just printed. Refuses to build if those files are missing.

Sections (per T7.2 contract):
  portal uploads | what this is | the mechanism | run it in 60 seconds |
  what to look at | capability ledger | evidence | repo map.

Usage:
    python3 scripts/build_readme_pdf.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "submission" / "ControlPlane_Round2_README.pdf"
EVAL_JSON = ROOT / "evals" / "last_run.json"
BENCH_JSON = ROOT / "submission" / "latency_bench.json"
PUBLIC_URL = "https://github.com/Srujan0798/controlplane-ai"


def _require_reportlab():
    try:
        from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT  # noqa: F401
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            ListFlowable,
            ListItem,
            PageBreak,
            Paragraph,
            Preformatted,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
        from reportlab.lib import colors
    except ImportError:
        print("reportlab required: pip install reportlab", file=sys.stderr)
        raise SystemExit(1)
    return {k: v for k, v in globals().items()} | {
        "A4": A4, "ParagraphStyle": ParagraphStyle,
        "getSampleStyleSheet": getSampleStyleSheet, "inch": inch,
        "ListFlowable": ListFlowable, "ListItem": ListItem,
        "PageBreak": PageBreak, "Paragraph": Paragraph,
        "Preformatted": Preformatted, "SimpleDocTemplate": SimpleDocTemplate,
        "Spacer": Spacer, "Table": Table, "TableStyle": TableStyle,
        "colors": colors, "TA_CENTER": TA_CENTER, "TA_JUSTIFY": TA_JUSTIFY,
        "TA_LEFT": TA_LEFT,
    }


def _load_numbers() -> dict:
    if not EVAL_JSON.exists() or not BENCH_JSON.exists():
        raise SystemExit(
            "evals/last_run.json and submission/latency_bench.json required — "
            "run `make eval` and `make bench` before building the README PDF"
        )
    raw = json.loads(EVAL_JSON.read_text())
    bench = json.loads(BENCH_JSON.read_text())
    ev = raw.get("summary", raw)
    if not ev.get("ungrounded_fnr_wilson") or not bench.get("gate_latency_ms"):
        raise SystemExit("eval/bench JSON missing FNR or gate_latency_ms")
    return {"eval": ev, "bench": bench}


def _navy_table(rl, data, col_widths):
    tbl = rl["Table"](data, colWidths=col_widths)
    tbl.setStyle(rl["TableStyle"]([
        ("BACKGROUND", (0, 0), (-1, 0), rl["colors"].navy),
        ("TEXTCOLOR", (0, 0), (-1, 0), rl["colors"].white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.4, rl["colors"].grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [rl["colors"].white, rl["colors"].whitesmoke]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return tbl


def build(out_path: Path = OUT) -> Path:
    rl = _require_reportlab()
    nums = _load_numbers()
    styles = rl["getSampleStyleSheet"]()
    title = rl["ParagraphStyle"]("t", parent=styles["Title"], fontSize=20, leading=24,
                                 alignment=rl["TA_CENTER"], spaceAfter=4)
    sub = rl["ParagraphStyle"]("s", parent=styles["Normal"], fontSize=11, leading=14,
                               alignment=rl["TA_CENTER"], textColor=rl["colors"].grey, spaceAfter=10)
    h1 = rl["ParagraphStyle"]("h1", parent=styles["Heading1"], fontSize=14, leading=18,
                              spaceBefore=14, spaceAfter=6)
    body = rl["ParagraphStyle"]("b", parent=styles["Normal"], fontSize=9.5, leading=13,
                                alignment=rl["TA_JUSTIFY"], spaceAfter=6)
    mono = rl["ParagraphStyle"]("m", parent=styles["Code"], fontSize=8.5, leading=11,
                                backColor=rl["colors"].whitesmoke, borderPadding=6, spaceAfter=6)
    small = rl["ParagraphStyle"]("sm", parent=styles["Normal"], fontSize=8, leading=10,
                                 textColor=rl["colors"].grey)

    def P(t, st=body):
        return rl["Paragraph"](t, st)

    def esc(t: str) -> str:
        return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    story = []

    story.append(P("ControlPlane.ai — Admission-Control Layer for AI That Acts", title))
    story.append(P("Accenture Innovation Challenge 2026 · Round 2 · Team ControlPlane · PS #1", sub))
    story.append(P(f"Public GitHub: {PUBLIC_URL}  ·  branch main  ·  tag v0.2.0-round2", sub))

    story.append(P("1. Portal uploads (five fields)", h1))
    story.append(P(
        "These are the only artifacts the submission portal needs. This PDF is field 3.", body))
    portal = [
        ["#", "Portal field", "Artifact"],
        ["1", "Public GitHub link", PUBLIC_URL],
        ["2", "Prototype video", "submission/ControlPlane_Round2_Prototype.mp4"],
        ["3", "README document (PDF)", "submission/ControlPlane_Round2_README.pdf"],
        ["4", "Business proposal (PDF)", "submission/ControlPlane_Round2_Proposal.pdf"],
        ["5", "Pitch deck (PPTX)", "submission/ControlPlane_Round2_Pitch.pptx"],
    ]
    story.append(_navy_table(rl, portal, [0.4 * rl["inch"], 2.0 * rl["inch"], 4.0 * rl["inch"]]))
    story.append(rl["Spacer"](1, 8))

    story.append(P("2. What this is", h1))
    story.append(P(
        "Every AI response that asks permission to <b>act</b> — issue a refund, send an email, "
        "publish a record — is a set of <b>claims</b>. ControlPlane captures provenance "
        "<b>outside</b> the model (STEP → SPAN → CLAIM → ACTION) and admits or holds each action "
        "through a frozen interlock matrix. Unproven claims cannot authorize irreversible actions. "
        "Lane 1 is deterministic; no LLM sits on the critical path.", body))
    story.append(P(
        "This repository is the working prototype. The numbers in the evidence section are produced "
        "by <font face='Courier' size='9'>make eval</font> and <font face='Courier' size='9'>make bench</font> "
        "and are regenerated on every run — they are measured, not asserted.", body))

    story.append(P("3. The mechanism", h1))
    story.append(P(
        "Run any response text through extract → bind → entitle → interlock → shadow:", body))
    story.append(P(
        "• <b>extract</b> — Lane-1 segmenter produces typed claims (numeric / structural / temporal / "
        "textual / derived) with hedging and role-in-action, no LLM.<br/>"
        "• <b>bind</b> — each claim is matched to provenance spans: BM25 + lexical gate (textual), "
        "Indian/Western numeric normalization (numeric), symbol-table lookup (structural), recompute "
        "(derived). Middle band → UNKNOWN, never a default pass.<br/>"
        "• <b>entitle</b> — span ACL is checked against principal clearance; an unbound PII entity is a "
        "leak (Rule A) → Block at R2/R3.<br/>"
        "• <b>interlock</b> — a frozen 16-cell matrix maps (blast-tier × verdict-column) to one of five "
        "actuators. The matrix is never redrawn.<br/>"
        "• <b>shadow</b> — every decision is dual-emitted; the published FNR carries a Wilson interval.", body))

    story.append(P("4. Run it in 60 seconds (clean clone)", h1))
    run_cmds = (
        f"git clone {PUBLIC_URL} && cd controlplane-ai\n"
        "python3 -m venv .venv && source .venv/bin/activate\n"
        "pip install -e \".[dev]\"\n"
        "bash scripts/preflight-lite.sh          # must PASS\n"
        "make run                                # http://127.0.0.1:8787\n"
        "# refund:  http://127.0.0.1:8787/?scenario=refund&mode=enforce&autorun=1\n"
        "# expected: show_text → Edit · issue_refund → Escalate (held)\n"
        "# gate:     http://127.0.0.1:8787/gate   (arbitrary text, no fixtures)\n"
        "make eval                               # FNR with Wilson CI\n"
        "make verify                             # tests + content laws + number freeze"
    )
    story.append(rl["Preformatted"](run_cmds, mono))
    story.append(P(
        "Refund language is <b>held and escalated with the evidence packet</b> — never 'blocked'.",
        small,
    ))

    story.append(P("5. What to look at", h1))
    story.append(P(
        "• <b>/gate</b> — paste a response; watch claims, binding method + rationale, symbol table, "
        "matrix cell, actuator, evidence packet, dead compute, per-stage latency.<br/>"
        "• <b>refund autorun</b> — show_text → Edit · issue_refund → Escalate (held).<br/>"
        "• <b>examples/refund_trace_demo.py</b> — same dual-action with fixtures off; amount via numeric.<br/>"
        "• <b>evals/cases/</b> — labelled cases incl. hard negatives; this is the corpus a judge "
        "can attack.<br/>"
        "• <b>controlplane/interlock.py</b> MATRIX — the sixteen transcribed cells, sole decider.", body))

    story.append(rl["PageBreak"]())

    story.append(P("6. Capability ledger", h1))
    story.append(P(
        "Every mechanism in the architecture, marked honestly: "
        "<b>implemented and tested</b> / <b>implemented, prototype-grade</b> / "
        "<b>designed, not built</b>. This preempts 'is any of this real?' by answering first.", body))
    ledger = [
        ("Claim extraction (Lane 1, no LLM)", "implemented and tested", "controlplane/extract.py"),
        ("Numeric normalization (IN/US grouping)", "implemented and tested", "controlplane/numeric.py"),
        ("BM25 + lexical entailment gate", "implemented and tested", "controlplane/bm25.py"),
        ("Symbol table / structural lookup", "implemented and tested", "controlplane/symbols.py"),
        ("Binder v2 route dispatch", "implemented and tested", "controlplane/binder.py"),
        ("PII Rule A (leak → Block)", "implemented and tested", "controlplane/pii.py"),
        ("Entitlement / ACL audit", "implemented and tested", "controlplane/entitlement.py"),
        ("Frozen 16-cell interlock matrix", "implemented and tested", "controlplane/interlock.py"),
        ("Lane deadlines (async gather)", "implemented and tested", "controlplane/lanes.py"),
        ("Hash-chained evidence ledger", "implemented and tested", "controlplane/ledger.py"),
        ("Override HTTP → chained ledger", "implemented and tested", "controlplane/server/app.py"),
        ("Analyze arbitrary text", "implemented and tested", "POST /v1/controlplane/analyze"),
        ("OpenAI-compatible FastAPI gate", "implemented and tested", "controlplane/server/app.py"),
        ("Dual-action refund (Edit + Escalate held)", "implemented and tested", "examples/refund_trace_demo.py"),
        ("Eval harness + Wilson CIs", "implemented and tested", "evals/run.py"),
        ("Load bench n=10000", "implemented and tested", "scripts/load_bench.py"),
        ("published_fnr from last eval", "implemented and tested", "GET /v1/controlplane/metrics"),
        ("Shadow-replay threshold gate", "implemented and tested", "controlplane/feedback.py"),
        ("Canary auto-rollback", "implemented and tested", "controlplane/feedback.py"),
        ("Jurisdiction packs (EU/IN/GDPR)", "implemented and tested", "policies/*.yaml"),
        ("Multi-turn claim inheritance", "implemented and tested", "controlplane/session.py"),
        ("Economist / dead-compute walk", "implemented and tested", "controlplane/economist.py"),
        ("Bias counterfactual (Lane 3)", "implemented, prototype-grade", "controlplane/bias.py"),
        ("GPU / trained NLI adapter", "designed, not built", "Lane-2 slot (stub)"),
        ("Production FNR on live traffic", "designed, not built", "shadow earn-out"),
        ("Production IAM repair", "designed, not built", "out of Round 2 scope"),
    ]
    data = [["Mechanism", "Status", "Where"]]
    for name, status, where in ledger:
        data.append([esc(name), esc(status), esc(where)])
    story.append(_navy_table(
        rl, data, [2.7 * rl["inch"], 1.7 * rl["inch"], 2.0 * rl["inch"]]
    ))

    story.append(P("7. Evidence (measured on this run)", h1))
    ev = nums["eval"]
    fnr = ev["ungrounded_fnr_wilson"]
    fpr = ev.get("passable_fpr_wilson") or [0, 0, 0]
    hn = ev.get("hard_negative_hold_wilson") or [0, 0, 0]
    a = ev.get("action_level", {})
    ungrounded = a.get("ungrounded") or {}
    miss_ids = ungrounded.get("miss_ids") or []
    n_ungrounded = int(ungrounded.get("held") or 0) + int(ungrounded.get("missed") or 0)
    story.append(P(
        f"Eval corpus: <b>{ev.get('n_cases', '?')}</b> labelled cases "
        f"({ev.get('n_bindings', '?')} bindings), <b>self-authored</b>. "
        f"Ungrounded FNR <b>{fnr[0]:.1%}</b> "
        f"(95% CI {fnr[1]:.1%}–{fnr[2]:.1%}"
        + (f"; n={n_ungrounded} ungrounded" if n_ungrounded else "")
        + "). "
        f"We HOLD <b>{(1 - fnr[0]):.1%}</b> of ungrounded responses. "
        f"Passable-action false-hold (FPR) <b>{fpr[0]:.1%}</b> "
        f"(95% CI {fpr[1]:.1%}–{fpr[2]:.1%}). "
        f"Fail-closed caution on hard-negatives <b>{hn[0]:.1%}</b>. "
        f"Abstention (UNKNOWN rate) <b>{ev.get('abstention_rate', 0):.1%}</b> of bindings.", body))
    if miss_ids:
        story.append(P(
            "Published miss"
            + ("es" if len(miss_ids) != 1 else "")
            + ": "
            + ", ".join(f"<font face='Courier' size='9'>{esc(str(m))}</font>" for m in miss_ids)
            + " (see evals/last_run.json).", body))
    pr = ev.get("per_route", {})
    if pr:
        rdata = [["Route", "n", "supported", "unknown", "contradicted", "unsupported", "abstain"]]
        for route, m in pr.items():
            rdata.append([
                route, str(m.get("n", "")), str(m.get("supported", "")),
                str(m.get("unknown", "")), str(m.get("contradicted", "")),
                str(m.get("unsupported", "")), f"{m.get('abstention_rate', 0):.1%}",
            ])
        story.append(rl["Paragraph"]("Per-route binding distribution:", small))
        story.append(_navy_table(
            rl, rdata,
            [1.1 * rl["inch"], 0.5 * rl["inch"], 1.0 * rl["inch"],
             0.8 * rl["inch"], 1.05 * rl["inch"], 1.0 * rl["inch"], 0.8 * rl["inch"]],
        ))

    bench = nums["bench"]
    g = bench.get("gate_latency_ms", {})
    story.append(P(
        f"Load bench: n={bench.get('n')} at concurrency sweep {bench.get('concurrencies')}. "
        f"Per-request compute p50={g.get('p50')} ms, p95={g.get('p95')} ms, p99={g.get('p99')} ms, "
        f"mean={g.get('mean')} ms, max={g.get('max')} ms. "
        f"Best throughput {bench.get('best_throughput_rps')} rps. "
        f"(In-process compute, not API latency; 40ms is a Lane-1 target, never a measured p95.)", body))

    story.append(P(
        "Refund language in this system is <b>held and escalated with the evidence packet</b> — never "
        "'blocked'. Irreversible actions are not released without provenance.", body))

    story.append(P("7.1 Honest reading of these numbers", h1))
    caution = a.get("hard_negative_caution") or {}
    hn_total = caution.get("total")
    n_h = ev.get("n_cases")
    hn_share = f"{(hn_total / n_h):.1%}" if hn_total and n_h else "n/a"
    story.append(P(
        f"Measured on a <b>{n_h}-case self-authored corpus</b>. Ungrounded FNR "
        f"<b>{fnr[0]:.1%}</b> (95% CI {fnr[1]:.1%}–{fnr[2]:.1%}), passable FPR "
        f"<b>{fpr[0]:.1%}</b> (95% upper bound {fpr[2]:.1%}). Hard-negative hold rate is "
        f"<b>{hn[0]:.0%}</b> ({hn[0]:.1%}, 95% Wilson CI {hn[1]:.1%}–{hn[2]:.1%}"
        + (f"; {hn_total}/{n_h} = {hn_share} hard negatives" if hn_total and n_h else "")
        + ") — we over-flag, we measured it, and it is our named next milestone. "
        "No production traffic; production FNR is unknown. The corpus ships in the repo so you can attack it.",
        body,
    ))

    story.append(P("7.2 What we refuse to claim", h1))
    story.append(P(
        "This list is about <b>us</b>, not about anyone else. <b>We do not claim:</b> "
        "elimination of hallucinations · zero integration cost · zero added latency · "
        "one accuracy number · production-scale proof.", body))

    story.append(P("8. Repo map", h1))
    story.append(P(
        "controlplane/ — pipeline (extract, binder, symbols, bm25, numeric, pii, entitlement, "
        "interlock, lanes, feedback, bias, shadow, server)<br/>"
        "evals/ — corpus (cases/), harness (run.py), Wilson CIs, last_run.json<br/>"
        "policies/ — jurisdiction packs (eu / in / gdpr / default)<br/>"
        "scripts/ — bench, proposal/readme PDF builders, preflight, verify<br/>"
        "examples/ — refund_trace_demo, knowledge_flip_demo, multi_usecase_demo<br/>"
        "submission/ — five portal files: mp4 · README.pdf · Proposal.pdf · Pitch.pptx<br/>"
        f"Public GitHub — {PUBLIC_URL}", body))
    story.append(P(
        "Content laws (ARCHITECTURE §10) are enforced in CI: pytest tests/test_content_laws.py.",
        small,
    ))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    rl["SimpleDocTemplate"](
        str(out_path), pagesize=rl["A4"],
        leftMargin=0.8 * rl["inch"], rightMargin=0.8 * rl["inch"],
        topMargin=0.7 * rl["inch"], bottomMargin=0.7 * rl["inch"],
        title="ControlPlane.ai README",
        author="Team ControlPlane",
    ).build(story)
    return out_path


if __name__ == "__main__":
    p = build()
    print(f"wrote {p} ({p.stat().st_size} bytes)")
